batch_size: 128
dataset:
  data_path: data/finetuning_set_smiles_plus_features.csv
  feature_cols:
  - desc_ABC/10
  - desc_ABCGG/10
  - desc_nBase
  - desc_SpAbs_A/30
  - desc_SpMax_A
  - desc_SpDiam_A
  - desc_SpAD_A/30
  - desc_SpMAD_A
  - desc_LogEE_A
  - desc_VE1_A
  - desc_VE2_A
  - desc_log_VR1_A
  - desc_log_VR2_A
  - desc_VR3_A/10
  - desc_nAromAtom
  - desc_nAromBond
  - desc_nAtom/30
  - desc_nHeavyAtom/10
  - desc_nHetero
  - desc_nH/30
  - desc_nC/10
  - desc_nN
  - desc_ATS0dv/100
  - desc_ATS1dv/100
  - desc_ATS2dv/100
  - desc_ATS3dv/100
  - desc_ATS4dv/100
  - desc_ATS5dv/100
  - desc_ATS6dv/100
  - desc_ATS7dv/100
  - desc_ATS0d/100
  - desc_ATS1d/100
  - desc_ATS2d/100
  - desc_ATS3d/100
  - desc_ATS4d/100
  - desc_ATS5d/100
  - desc_ATS6d/100
  - desc_ATS7d/100
  - desc_ATS8d/100
  - desc_ATS0s/100
  - desc_ATS1s/100
  - desc_ATS2s/100
  - desc_ATS3s/100
  - desc_ATS4s/100
  - desc_ATS5s/100
  - desc_ATS6s/100
  - desc_ATS7s/100
  - desc_ATS8s/100
  - desc_ATS0Z/1000
  - desc_ATS1Z/1000
  - desc_ATS2Z/1000
  - desc_ATS3Z/1000
  - desc_ATS4Z/1000
  - desc_ATS5Z/1000
  - desc_ATS6Z/1000
  - desc_ATS7Z/1000
  - desc_ATS8Z/1000
  - desc_ATS0m/1000
  - desc_ATS1m/1000
  - desc_ATS2m/10000
  - desc_ATS3m/10000
  - desc_ATS4m/10000
  - desc_ATS5m/10000
  - desc_ATS6m/10000
  - desc_ATS7m/10000
  - desc_ATS8m/10000
  - desc_ATS0v/10000
  - desc_ATS1v/10000
  - desc_ATS2v/10000
  - desc_ATS3v/10000
  - desc_ATS4v/10000
  - desc_ATS5v/10000
  - desc_ATS6v/10000
  - desc_ATS7v/10000
  - desc_ATS8v/10000
  - desc_ATS0se/100
  - desc_ATS1se/1000
  - desc_ATS2se/1000
  - desc_ATS3se/1000
  - desc_ATS4se/1000
  - desc_ATS5se/1000
  - desc_ATS6se/1000
  - desc_ATS7se/1000
  - desc_ATS8se/1000
  - desc_ATS0pe/100
  - desc_ATS1pe/100
  - desc_ATS2pe/1000
  - desc_ATS3pe/1000
  - desc_ATS4pe/1000
  - desc_ATS5pe/1000
  - desc_ATS6pe/1000
  - desc_ATS7pe/1000
  - desc_ATS8pe/1000
  - desc_ATS0are/100
  - desc_ATS1are/100
  - desc_ATS2are/1000
  - desc_ATS3are/1000
  - desc_ATS4are/1000
  - desc_ATS5are/1000
  - desc_ATS6are/1000
  - desc_ATS7are/1000
  - desc_ATS8are/1000
  - desc_ATS0p/30
  - desc_ATS1p/100
  - desc_ATS2p/100
  - desc_ATS3p/100
  - desc_ATS4p/100
  - desc_ATS5p/100
  - desc_ATS6p/100
  - desc_ATS7p/100
  - desc_ATS8p/100
  - desc_ATS0i/10000
  - desc_ATS1i/10000
  - desc_ATS2i/10000
  - desc_ATS3i/10000
  - desc_ATS4i/10000
  - desc_ATS5i/10000
  - desc_ATS6i/10000
  - desc_ATS7i/10000
  - desc_ATS8i/10000
  - desc_AATS0dv
  - desc_AATS1dv
  - desc_AATS2dv
  - desc_AATS3dv
  - desc_AATS4dv
  - desc_AATS5dv
  - desc_AATS6dv
  - desc_AATS8dv
  - desc_AATS0d
  - desc_AATS1d
  - desc_AATS2d
  - desc_AATS3d
  - desc_AATS4d
  - desc_AATS5d
  - desc_AATS6d
  - desc_AATS7d
  - desc_AATS5s
  - desc_AATS6s
  - desc_AATS0Z/10
  - desc_AATS1Z/10
  - desc_AATS2Z/10
  - desc_AATS3Z
  - desc_AATS4Z
  - desc_AATS5Z
  - desc_AATS6Z
  - desc_AATS8Z
  - desc_AATS0m/10
  - desc_AATS1m/30
  - desc_AATS2m/10
  - desc_AATS3m/10
  - desc_AATS4m/10
  - desc_AATS5m/10
  - desc_AATS6m/10
  - desc_AATS8m/10
  - desc_AATS0v/30
  - desc_AATS1v/100
  - desc_AATS2v/30
  - desc_AATS3v/30
  - desc_AATS4v/30
  - desc_AATS5v/30
  - desc_AATS6v/30
  - desc_AATS7v/30
  - desc_AATS5se
  - desc_AATS6se
  - desc_AATS5pe
  - desc_AATS5are
  - desc_AATS6are
  - desc_AATS0p
  - desc_AATS1p
  - desc_AATS2p
  - desc_AATS3p
  - desc_AATS4p
  - desc_AATS5p
  - desc_AATS6p
  - desc_AATS7p
  - desc_AATS8p
  - desc_AATS0i/30
  - desc_AATS1i/30
  - desc_AATS2i/30
  - desc_AATS5i/30
  - desc_AATS6i/30
  - desc_AATS7i/30
  - desc_AATS8i/30
  - desc_ATSC0c
  - desc_ATSC1c
  - desc_ATSC5c
  - desc_ATSC8c
  - desc_ATSC0dv/100
  - desc_ATSC1dv/30
  - desc_ATSC2dv/30
  - desc_ATSC4dv/10
  - desc_ATSC5dv/10
  - desc_ATSC7dv/30
  - desc_ATSC8dv/10
  - desc_ATSC0d/10
  - desc_ATSC2d/10
  - desc_ATSC6d
  - desc_ATSC7d
  - desc_ATSC0s/30
  - desc_ATSC1s
  - desc_ATSC2s/10
  - desc_ATSC5s/10
  - desc_ATSC7s/10
  - desc_ATSC8s/10
  - desc_ATSC0Z/100
  - desc_ATSC1Z/10
  - desc_ATSC2Z/100
  - desc_ATSC4Z/30
  - desc_ATSC7Z/30
  - desc_ATSC8Z/30
  - desc_ATSC0m/1000
  - desc_ATSC1m/30
  - desc_ATSC2m/1000
  - desc_ATSC4m/100
  - desc_ATSC7m/100
  - desc_ATSC8m/100
  - desc_ATSC0v/1000
  - desc_ATSC1v/100
  - desc_ATSC2v/1000
  - desc_ATSC4v/100
  - desc_ATSC7v/100
  - desc_ATSC8v/100
  - desc_ATSC1se
  - desc_ATSC2se
  - desc_ATSC5se
  - desc_ATSC7se
  - desc_ATSC0pe
  - desc_ATSC1pe
  - desc_ATSC2pe
  - desc_ATSC5pe
  - desc_ATSC7pe
  - desc_ATSC8pe
  - desc_ATSC0are
  - desc_ATSC1are
  - desc_ATSC2are
  - desc_ATSC5are
  - desc_ATSC7are
  - desc_ATSC8are
  - desc_ATSC0p/10
  - desc_ATSC1p
  - desc_ATSC2p/10
  - desc_ATSC5p
  - desc_ATSC7p
  - desc_ATSC0i/30
  - desc_ATSC1i/10
  - desc_ATSC2i/30
  - desc_ATSC5i/10
  - desc_ATSC8i/10
  - desc_AATSC4c
  - desc_AATSC5c
  - desc_AATSC8c
  - desc_AATSC0dv
  - desc_AATSC1dv
  - desc_AATSC2dv
  - desc_AATSC4dv
  - desc_AATSC5dv
  - desc_AATSC7dv
  - desc_AATSC8dv
  - desc_AATSC2d
  - desc_AATSC6d
  - desc_AATSC7d
  - desc_AATSC1s
  - desc_AATSC2s
  - desc_AATSC3s
  - desc_AATSC5s
  - desc_AATSC8s
  - desc_AATSC1Z
  - desc_AATSC2Z
  - desc_AATSC4Z
  - desc_AATSC7Z
  - desc_AATSC8Z
  - desc_AATSC1m
  - desc_AATSC2m
  - desc_AATSC4m
  - desc_AATSC7m
  - desc_AATSC8m
  - desc_AATSC0v/10
  - desc_AATSC1v
  - desc_AATSC2v/10
  - desc_AATSC4v
  - desc_AATSC5v
  - desc_AATSC7v
  - desc_AATSC8v
  - desc_AATSC0se
  - desc_AATSC1se
  - desc_AATSC2se
  - desc_AATSC3se
  - desc_AATSC7se
  - desc_AATSC8se
  - desc_AATSC1pe
  - desc_AATSC2pe
  - desc_AATSC3pe
  - desc_AATSC7pe
  - desc_AATSC8pe
  - desc_AATSC1are
  - desc_AATSC2are
  - desc_AATSC3are
  - desc_AATSC7are
  - desc_AATSC8are
  - desc_AATSC0p
  - desc_AATSC1p
  - desc_AATSC2p
  - desc_AATSC5p
  - desc_AATSC0i
  - desc_AATSC1i
  - desc_AATSC2i
  - desc_AATSC5i
  - desc_AATSC8i
  - desc_MATS4c
  - desc_MATS5c
  - desc_MATS8c
  - desc_MATS1dv
  - desc_MATS2dv
  - desc_MATS4dv
  - desc_MATS5dv
  - desc_MATS7dv
  - desc_MATS8dv
  - desc_MATS2d
  - desc_MATS6d
  - desc_MATS7d
  - desc_MATS1s
  - desc_MATS2s
  - desc_MATS5s
  - desc_MATS7s
  - desc_MATS8s
  - desc_MATS1Z
  - desc_MATS2Z
  - desc_MATS4Z
  - desc_MATS7Z
  - desc_MATS8Z
  - desc_MATS1m
  - desc_MATS2m
  - desc_MATS4m
  - desc_MATS7m
  - desc_MATS8m
  - desc_MATS1v
  - desc_MATS2v
  - desc_MATS4v
  - desc_MATS5v
  - desc_MATS7v
  - desc_MATS8v
  - desc_MATS1se
  - desc_MATS2se
  - desc_MATS7se
  - desc_MATS8se
  - desc_MATS1pe
  - desc_MATS2pe
  - desc_MATS7pe
  - desc_MATS8pe
  - desc_MATS1are
  - desc_MATS2are
  - desc_MATS7are
  - desc_MATS8are
  - desc_MATS1p
  - desc_MATS2p
  - desc_MATS5p
  - desc_MATS1i
  - desc_MATS2i
  - desc_MATS5i
  - desc_MATS8i
  - desc_GATS1c
  - desc_GATS2c
  - desc_GATS4c
  - desc_GATS6c
  - desc_GATS7c
  - desc_GATS1dv
  - desc_GATS2dv
  - desc_GATS7dv
  - desc_GATS1d
  - desc_GATS2d
  - desc_GATS6d
  - desc_GATS8d
  - desc_GATS1s
  - desc_GATS2s
  - desc_GATS7s
  - desc_GATS1Z
  - desc_GATS2Z
  - desc_GATS7Z
  - desc_GATS8Z
  - desc_GATS1m
  - desc_GATS2m
  - desc_GATS7m
  - desc_GATS8m
  - desc_GATS1v
  - desc_GATS2v
  - desc_GATS3v
  - desc_GATS5v
  - desc_GATS8v
  - desc_GATS1se
  - desc_GATS2se
  - desc_GATS7se
  - desc_GATS1pe
  - desc_GATS2pe
  - desc_GATS6pe
  - desc_GATS7pe
  - desc_GATS1are
  - desc_GATS2are
  - desc_GATS6are
  - desc_GATS7are
  - desc_GATS1p
  - desc_GATS3p
  - desc_GATS5p
  - desc_GATS1i
  - desc_GATS5i
  - desc_GATS8i
  - desc_BCUTd-1h
  - desc_BCUTd-1l
  - desc_BCUTs-1h
  - desc_BCUTs-1l
  - desc_BCUTZ-1l
  - desc_BCUTm-1l/10
  - desc_BCUTv-1h/10
  - desc_BCUTse-1h
  - desc_BCUTse-1l
  - desc_BCUTpe-1h
  - desc_BCUTpe-1l
  - desc_BCUTare-1l
  - desc_BCUTp-1h
  - desc_BCUTp-1l
  - desc_BCUTi-1h/10
  - desc_BCUTi-1l/10
  - desc_BalabanJ
  - desc_SpAbs_DzZ/1000
  - desc_SpMax_DzZ/100
  - desc_SpDiam_DzZ/100
  - desc_SpAD_DzZ/1000
  - desc_SpMAD_DzZ/10
  - desc_LogEE_DzZ/100
  - desc_VE1_DzZ
  - desc_VE2_DzZ
  - desc_VE3_DzZ
  - desc_VR1_DzZ/100
  - desc_VR2_DzZ
  - desc_VR3_DzZ
  - desc_SpAbs_Dzm/1000
  - desc_SpMax_Dzm/100
  - desc_SpDiam_Dzm/100
  - desc_SpAD_Dzm/1000
  - desc_SpMAD_Dzm/10
  - desc_LogEE_Dzm/100
  - desc_VE1_Dzm
  - desc_VE2_Dzm
  - desc_VE3_Dzm
  - desc_VR1_Dzm/100
  - desc_VR2_Dzm
  - desc_VR3_Dzm
  - desc_SpAbs_Dzv/1000
  - desc_SpMax_Dzv/100
  - desc_SpDiam_Dzv/1000
  - desc_SpAD_Dzv/1000
  - desc_SpMAD_Dzv/10
  - desc_LogEE_Dzv/100
  - desc_VE1_Dzv
  - desc_VE2_Dzv
  - desc_VE3_Dzv
  - desc_VR1_Dzv/100
  - desc_VR2_Dzv
  - desc_VR3_Dzv
  - desc_SpAbs_Dzse/1000
  - desc_SpMax_Dzse/100
  - desc_SpDiam_Dzse/100
  - desc_SpAD_Dzse/1000
  - desc_SpMAD_Dzse/10
  - desc_LogEE_Dzse/100
  - desc_VE1_Dzse
  - desc_VE2_Dzse
  - desc_VE3_Dzse
  - desc_VR1_Dzse/100
  - desc_VR2_Dzse
  - desc_VR3_Dzse
  - desc_SpAbs_Dzpe/1000
  - desc_SpMax_Dzpe/100
  - desc_SpDiam_Dzpe/100
  - desc_SpAD_Dzpe/1000
  - desc_SpMAD_Dzpe/10
  - desc_LogEE_Dzpe/100
  - desc_VE1_Dzpe
  - desc_VE2_Dzpe
  - desc_VE3_Dzpe
  - desc_VR1_Dzpe/100
  - desc_VR2_Dzpe
  - desc_VR3_Dzpe
  - desc_SpAbs_Dzare/1000
  - desc_SpMax_Dzare/100
  - desc_SpDiam_Dzare/100
  - desc_SpAD_Dzare/1000
  - desc_SpMAD_Dzare/10
  - desc_LogEE_Dzare/100
  - desc_VE1_Dzare
  - desc_VE2_Dzare
  - desc_VE3_Dzare
  - desc_VR1_Dzare/100
  - desc_VR2_Dzare
  - desc_VR3_Dzare
  - desc_SpAbs_Dzp/1000
  - desc_SpMax_Dzp/100
  - desc_SpDiam_Dzp/1000
  - desc_SpAD_Dzp/1000
  - desc_SpMAD_Dzp/10
  - desc_LogEE_Dzp/100
  - desc_VE1_Dzp
  - desc_VE2_Dzp
  - desc_VE3_Dzp
  - desc_VR1_Dzp/100
  - desc_VR2_Dzp
  - desc_VR3_Dzp
  - desc_SpAbs_Dzi/1000
  - desc_SpMax_Dzi/100
  - desc_SpDiam_Dzi/100
  - desc_SpAD_Dzi/1000
  - desc_SpMAD_Dzi/10
  - desc_LogEE_Dzi/100
  - desc_SM1_Dzi
  - desc_VE1_Dzi
  - desc_VE2_Dzi
  - desc_VE3_Dzi
  - desc_VR1_Dzi/100
  - desc_VR2_Dzi
  - desc_VR3_Dzi
  - desc_BertzCT/100
  - desc_nBonds/30
  - desc_nBondsO/10
  - desc_nBondsS/30
  - desc_nBondsD
  - desc_nBondsT
  - desc_nBondsA
  - desc_nBondsM
  - desc_nBondsKS/30
  - desc_nBondsKD
  - desc_RNCG
  - desc_RPCG
  - desc_C1SP1
  - desc_C2SP1
  - desc_C1SP2
  - desc_C2SP2
  - desc_C1SP3/10
  - desc_C2SP3/10
  - desc_C3SP3
  - desc_HybRatio
  - desc_FCSP3
  - desc_Xch-5d
  - desc_Xch-6d
  - desc_Xch-7d
  - desc_Xch-6dv
  - desc_Xch-7dv
  - desc_Xc-5d
  - desc_Xpc-6d
  - desc_Xpc-6dv
  - desc_Xp-0d/10
  - desc_Xp-1d/10
  - desc_Xp-2d/10
  - desc_Xp-3d/10
  - desc_Xp-4d
  - desc_Xp-5d
  - desc_Xp-6d
  - desc_Xp-7d
  - desc_AXp-0d
  - desc_AXp-1d
  - desc_AXp-3d
  - desc_AXp-4d
  - desc_AXp-5d
  - desc_AXp-6d
  - desc_AXp-7d
  - desc_Xp-0dv/10
  - desc_Xp-1dv/10
  - desc_Xp-2dv/10
  - desc_Xp-3dv/10
  - desc_Xp-4dv
  - desc_Xp-5dv
  - desc_Xp-6dv
  - desc_Xp-7dv
  - desc_AXp-0dv
  - desc_AXp-1dv
  - desc_AXp-2dv
  - desc_AXp-3dv
  - desc_AXp-4dv
  - desc_AXp-5dv
  - desc_AXp-6dv
  - desc_AXp-7dv
  - desc_SZ/30
  - desc_Sm/10
  - desc_Sv/30
  - desc_Sse/30
  - desc_Spe/30
  - desc_Sare/30
  - desc_Sp/30
  - desc_Si/30
  - desc_MZ
  - desc_Mm
  - desc_Mv
  - desc_Mp
  - desc_Mi
  - desc_SpAbs_D/1000
  - desc_SpMax_D/100
  - desc_SpDiam_D/1000
  - desc_SpAD_D/1000
  - desc_SpMAD_D/10
  - desc_LogEE_D/100
  - desc_VE1_D
  - desc_VE2_D
  - desc_VE3_D
  - desc_VR1_D/100
  - desc_VR2_D
  - desc_VR3_D
  - desc_NsCH3
  - desc_NssCH2/10
  - desc_NtCH
  - desc_NdsCH
  - desc_NaaCH
  - desc_NsssCH
  - desc_NtsC
  - desc_NaasC
  - desc_NsNH2
  - desc_NssNH
  - desc_NaaNH
  - desc_NaaN
  - desc_NsssN
  - desc_NaasN
  - desc_SsCH3
  - desc_SssCH2/10
  - desc_StCH
  - desc_SdsCH
  - desc_SaaCH
  - desc_SsssCH
  - desc_StsC
  - desc_log_SdssC
  - desc_SaasC
  - desc_SsNH2/10
  - desc_SssNH
  - desc_SaaNH
  - desc_SaaN
  - desc_SsssN
  - desc_SaasN
  - desc_SdO/10
  - desc_MAXsssCH
  - desc_MAXdssC
  - desc_MAXssNH
  - desc_MAXdO/10
  - desc_MINssCH2
  - desc_MINsssCH
  - desc_MINdssC
  - desc_MINssNH
  - desc_MINdO/10
  - desc_ECIndex/1000
  - desc_ETA_alpha/10
  - desc_ETA_shape_p
  - desc_ETA_beta/10
  - desc_AETA_beta
  - desc_ETA_beta_s/10
  - desc_ETA_beta_ns
  - desc_AETA_beta_ns
  - desc_ETA_beta_ns_d
  - desc_AETA_beta_ns_d
  - desc_ETA_eta/30
  - desc_ETA_eta_L/10
  - desc_AETA_eta_L
  - desc_ETA_eta_R/30
  - desc_AETA_eta_R
  - desc_ETA_eta_RL/10
  - desc_AETA_eta_RL
  - desc_ETA_eta_F/10
  - desc_AETA_eta_F
  - desc_ETA_eta_FL
  - desc_AETA_eta_FL
  - desc_AETA_eta_BR
  - desc_ETA_epsilon_3
  - desc_ETA_epsilon_5
  - desc_ETA_dEpsilon_B
  - desc_ETA_dEpsilon_C
  - desc_ETA_dEpsilon_D
  - desc_ETA_dBeta/10
  - desc_AETA_dBeta
  - desc_fragCpx/10
  - desc_fMF
  - desc_nHBAcc
  - desc_nHBDon
  - desc_IC1
  - desc_IC5
  - desc_TIC0/30
  - desc_TIC1/100
  - desc_TIC2/100
  - desc_TIC3/100
  - desc_TIC4/100
  - desc_TIC5/100
  - desc_SIC1
  - desc_BIC1
  - desc_CIC0
  - desc_MIC1/10
  - desc_ZMIC0/100
  - desc_ZMIC1/30
  - desc_Kier1/10
  - desc_Kier2/10
  - desc_Kier3/10
  - desc_VMcGowan/100
  - desc_LabuteASA/100
  - desc_PEOE_VSA1/10
  - desc_PEOE_VSA2/10
  - desc_PEOE_VSA3/10
  - desc_PEOE_VSA4
  - desc_PEOE_VSA5/10
  - desc_PEOE_VSA8/10
  - desc_PEOE_VSA10/10
  - desc_SMR_VSA3/10
  - desc_SMR_VSA4/10
  - desc_SMR_VSA6/10
  - desc_SMR_VSA7/10
  - desc_SMR_VSA9/10
  - desc_SlogP_VSA1/10
  - desc_SlogP_VSA2/30
  - desc_SlogP_VSA3/10
  - desc_SlogP_VSA6/10
  - desc_SlogP_VSA10
  - desc_EState_VSA4/30
  - desc_EState_VSA6/10
  - desc_EState_VSA7/10
  - desc_EState_VSA9
  - desc_VSA_EState2/10
  - desc_VSA_EState3
  - desc_VSA_EState6
  - desc_VSA_EState7/10
  - desc_VSA_EState8/10
  - desc_MDEC-11
  - desc_MDEC-23/10
  - desc_MDEC-33
  - desc_MID/30
  - desc_AMID
  - desc_MID_C/30
  - desc_AMID_C
  - desc_MID_N
  - desc_AMID_O
  - desc_MPC2/10
  - desc_MPC3/10
  - desc_MPC4/10
  - desc_MPC5/30
  - desc_MPC6/10
  - desc_MPC7/30
  - desc_MPC8/30
  - desc_MPC9/30
  - desc_MPC10/30
  - desc_TMPC10/100
  - desc_piPC1
  - desc_piPC2
  - desc_piPC3
  - desc_piPC4
  - desc_piPC5
  - desc_piPC6
  - desc_piPC7
  - desc_piPC8
  - desc_piPC9
  - desc_piPC10
  - desc_TpiPC10
  - desc_apol/30
  - desc_bpol/30
  - desc_nRing
  - desc_n5Ring
  - desc_n6Ring
  - desc_nHRing
  - desc_n5HRing
  - desc_n6HRing
  - desc_naRing
  - desc_n5aRing
  - desc_naHRing
  - desc_n5aHRing
  - desc_nARing
  - desc_n6ARing
  - desc_nAHRing
  - desc_n6AHRing
  - desc_nRot/10
  - desc_RotRatio
  - desc_SLogP/10
  - desc_SMR/100
  - desc_TopoPSA(NO)/30
  - desc_TopoPSA/30
  - desc_GGI8
  - desc_GGI10
  - desc_JGI1
  - desc_JGI2
  - desc_JGI3
  - desc_JGI8
  - desc_JGI10
  - desc_JGT10
  - desc_Diameter/10
  - desc_Radius/10
  - desc_TopoShapeIndex
  - desc_PetitjeanIndex
  - desc_Vabc/100
  - desc_VAdjMat
  - desc_MWC01/10
  - desc_MWC02
  - desc_MWC03
  - desc_MWC04
  - desc_MWC05
  - desc_MWC06
  - desc_MWC07
  - desc_MWC08
  - desc_MWC09/10
  - desc_MWC10/10
  - desc_TMWC10/30
  - desc_SRW02
  - desc_SRW04
  - desc_SRW05
  - desc_SRW06
  - desc_SRW07
  - desc_SRW08
  - desc_SRW09
  - desc_SRW10
  - desc_MW/100
  - desc_AMW
  - desc_WPath/10000
  - desc_WPol/10
  - desc_Zagreb1/100
  - desc_Zagreb2/100
  - desc_mZagreb2/10
  generator_seed: 2
  library_split_seed: 2
  num_workers: 4
  splitting: library
  target: expt_Hela
  task: regression
  test_size: 0.1
  valid_size: 0.1
dir_header: AGILE_MA_library_HeLa/iter2/HP4
dir_name_root: library_iter2_HP4
epochs: 30
eval_every_n_epochs: 1
fine_tune_from: pretrained_agile_60k
fp16_precision: false
gpu: cuda:2
init_base_lr: 0.0001
init_lr: 0.0005
log_every_n_steps: 5
model:
  drop_ratio: 0.1
  emb_dim: 300
  feat_dim: 512
  num_layer: 5
  pool: mean
  pred_additional_feat_dim: 813
seed: 2
summary_file: AGILE_MA_library_HeLa.csv
task_name: lnp_hela_with_feat
weight_decay: 1e-6
